
Currently Loaded Modules:
  1) tensorflow/2.6.0

 

2025-07-09 18:51:21.931268: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1938] TensorFlow was not built with CUDA kernel binaries compatible with compute capability 10.0. CUDA kernels will be jit-compiled from PTX, which could take 30 minutes or longer.
2025-07-09 18:52:16.230797: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1938] TensorFlow was not built with CUDA kernel binaries compatible with compute capability 10.0. CUDA kernels will be jit-compiled from PTX, which could take 30 minutes or longer.
2025-07-09 18:52:16.231300: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2025-07-09 18:52:16.237539: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1938] TensorFlow was not built with CUDA kernel binaries compatible with compute capability 10.0. CUDA kernels will be jit-compiled from PTX, which could take 30 minutes or longer.
2025-07-09 18:52:28.386571: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1510] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 180450 MB memory:  -> device: 0, name: NVIDIA B200, pci bus id: 0000:d1:00.0, compute capability: 10.0
2025-07-09 18:52:30.785058: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:185] None of the MLIR Optimization Passes are enabled (registered 2)
2025-07-09 18:52:34.542565: I tensorflow/stream_executor/cuda/cuda_blas.cc:1760] TensorFloat-32 will be used for the matrix multiplication. This will only be logged once.
2025-07-09 18:52:34.569353: W tensorflow/core/framework/op_kernel.cc:1680] Invalid argument: required broadcastable shapes
<frozen importlib._bootstrap>:219: RuntimeWarning: scipy._lib.messagestream.MessageStream size changed, may indicate binary incompatibility. Expected 56 from C header, got 64 from PyObject
Traceback (most recent call last):
  File "train_gnn.py", line 420, in <module>
    main()
  File "train_gnn.py", line 394, in main
    loss = loss_fn(y_true, y_pred)
  File "/home/jruizmunoz/anaconda3/envs/ghifo_py38/lib/python3.8/site-packages/keras/losses.py", line 141, in __call__
    losses = call_fn(y_true, y_pred)
  File "/home/jruizmunoz/anaconda3/envs/ghifo_py38/lib/python3.8/site-packages/keras/losses.py", line 245, in call
    return ag_fn(y_true, y_pred, **self._fn_kwargs)
  File "/home/jruizmunoz/anaconda3/envs/ghifo_py38/lib/python3.8/site-packages/tensorflow/python/util/dispatch.py", line 206, in wrapper
    return target(*args, **kwargs)
  File "/home/jruizmunoz/anaconda3/envs/ghifo_py38/lib/python3.8/site-packages/keras/losses.py", line 1204, in mean_squared_error
    return backend.mean(tf.math.squared_difference(y_pred, y_true), axis=-1)
  File "/home/jruizmunoz/anaconda3/envs/ghifo_py38/lib/python3.8/site-packages/tensorflow/python/ops/gen_math_ops.py", line 10497, in squared_difference
    _ops.raise_from_not_ok_status(e, name)
  File "/home/jruizmunoz/anaconda3/envs/ghifo_py38/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 6941, in raise_from_not_ok_status
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError: required broadcastable shapes [Op:SquaredDifference]
