
The following have been reloaded with a version change:
  1) cuda/12.9.1 => cuda/12.4.1


Currently Loaded Modules:
  1) cuda/12.4.1   2) tensorflow/2.18

 

<frozen importlib._bootstrap>:219: RuntimeWarning: scipy._lib.messagestream.MessageStream size changed, may indicate binary incompatibility. Expected 56 from C header, got 64 from PyObject
<frozen importlib._bootstrap>:219: RuntimeWarning: scipy._lib.messagestream.MessageStream size changed, may indicate binary incompatibility. Expected 56 from C header, got 64 from PyObject
Traceback (most recent call last):
  File "train_gnn.py", line 516, in <module>
    main()
  File "train_gnn.py", line 330, in main
    model = build_gnn_model(input_shape=(num_features,), output_units=FORECAST_HORIZON)
  File "train_gnn.py", line 247, in build_gnn_model
    x = layers.Lambda(aggregate_nodes)([x, i_in])
  File "/home/jruizmunoz/anaconda3/envs/ghifo_py38/lib/python3.8/site-packages/keras/engine/base_layer.py", line 976, in __call__
    return self._functional_construction_call(inputs, args, kwargs,
  File "/home/jruizmunoz/anaconda3/envs/ghifo_py38/lib/python3.8/site-packages/keras/engine/base_layer.py", line 1114, in _functional_construction_call
    outputs = self._keras_tensor_symbolic_call(
  File "/home/jruizmunoz/anaconda3/envs/ghifo_py38/lib/python3.8/site-packages/keras/engine/base_layer.py", line 848, in _keras_tensor_symbolic_call
    return self._infer_output_signature(inputs, args, kwargs, input_masks)
  File "/home/jruizmunoz/anaconda3/envs/ghifo_py38/lib/python3.8/site-packages/keras/engine/base_layer.py", line 888, in _infer_output_signature
    outputs = call_fn(inputs, *args, **kwargs)
  File "/home/jruizmunoz/anaconda3/envs/ghifo_py38/lib/python3.8/site-packages/keras/layers/core.py", line 903, in call
    result = self.function(inputs, **kwargs)
  File "train_gnn.py", line 238, in aggregate_nodes
    aggregated_features = tf.unsorted_segment_mean(
AttributeError: module 'tensorflow' has no attribute 'unsorted_segment_mean'
